#!/bin/sh

set -e

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"

make -s bin/golangci-lint bin/shellcheck
bin/shellcheck script/*

linter="$(pwd)/bin/golangci-lint"

for f in ./*/go.mod; do
  (
    cd "$(dirname "$f")"
    "$linter" run
  )
done
