#!/bin/sh

set -e

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"

make -s bin/golangci-lint bin/shellcheck
bin/shellcheck script/*

linter="$(pwd)/bin/golangci-lint"
export linter

find . -name "go.mod" -exec sh -c '
  cd "$(dirname $0)"
  "$linter" run
' {} \;
