name: ci
on: [push]
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x]
    runs-on: ubuntu-latest
    steps:
    - name: Set up go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: lint
      run: script/lint
    - name: test
      run: script/test
